# AreYouTyping v.1.0 by Orphey98
# https://github.com/Orphey98

#Show player names in hologram.
show-names: true
#Indentation style of typing icon. Makes sense only with show-names enabled
icon-indentation: true
#Hologram visibility distance
view-range: 16
#Hologram visibility through blocks
visible-through-blocks: false
#UNICODE character or text (up to 12 characters) for typing animation.
typing-char: "✎"

#Color customization
names-color: "#ffffff"
typing-icon-color: "#ffffff"
background-color: "#000000"
#From 0 to 255
background-transparency: 50
#Shadow outline of text font
text-shadow: false

#Changing these values are not recommended
#Attached hologram spawn location offset, relative to player position.