name: TypingInChat
version: '1.0'
main: me.orphey.typinginchat.TypingInChat
api-version: '1.19'
depend: [HologramLib, packetevents]
softdepend: [VaultAPI]
commands:
  typinginchat:
    description: "TypingInChat plugin main command"
    usage: "/typinginchat reload"
    aliases: [tic]
    permission: tic.admin
    permission-message: "You do not have tic.admin permission"
permissions:
  tic.admin:
    description: "Access to </tic reload> command"
    default: op
  tic.display:
    description: "Show chat typing hologram for the player"
    default: true

